### ISSUE TITLE
모임 필터링 조회 무한루프로 인한 커넥션 풀 고갈 현상 수정

### ISSUE THREAD

**Issue by J-I-H-O** [woowacourse-teams/2024-friendogly#682]
## 요구 사항
- 현재 모임 `참여 가능` 조건으로 조회 시 응답을 해주지 못하고 있음 
- 클라이언트는 서버로부터 응답을 받지 못해 타임 아웃이 발생함
- 모종의 이유로 `참여 가능` 모임 조회 시 무한 루프 도는 것으로 추정
- 해당 요청을 계속해서 보내면 커넥션이 반납되지 않아 커넥션 풀이 고갈되고, 다른 모든 요청 처리가 불가능해지는 상황이 발생함

```java
Caused by: java.sql.SQLTransientConnectionException: HikariPool-1 - Connection is not available, request timed out after 30008ms (total=10, active=10, idle=0, waiting=0)
        at com.zaxxer.hikari.pool.HikariPool.createTimeoutException(HikariPool.java:686)
        at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:179)
        at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:144)
        at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:127)
        at org.hibernate.engine.jdbc.connections.internal.DatasourceConnectionProviderImpl.getConnection(DatasourceConnectionProviderImpl.java:122)
        at org.hibernate.internal.NonContextualJdbcConnectionAccess.obtainConnection(NonContextualJdbcConnectionAccess.java:46)
        at org.hibernate.resource.jdbc.internal.LogicalConnectionManagedImpl.acquireConnectionIfNeeded(LogicalConnectionManagedImpl.java:113)
        ... 66 common frames omitted
```

**Comment by J-I-H-O** [comment]
### 문제 원인
- 다음 페이지 조회 조건으로 사용되는 정보를 정상적으로 업데이트 해주지 못하고 있어 반복문이 종료되지 않고 있었음

### as-is

```java
    private LocalDateTime updateLastFoundCreatedAt(LocalDateTime lastFoundCreatedAt, List<Club> result) {
        if (result.isEmpty()) {
            return lastFoundCreatedAt;
        }
        return result.get(result.size() - 1).getCreatedAt();
    }

    private Long updateLastFoundId(Long lastFoundId, List<Club> result) {
        if (result.isEmpty()) {
            return lastFoundId;
        }
        return result.get(result.size() - 1).getId();
    }
```
- 한 페이지에 조회 결과가 없는 경우, 클라이언트가 보내준 lastFoundCreatedAt과 lastFoundId를 다음 페이지 조회 조건으로 그대로 재사용하고 있음
- -> 페이지 조회 조건이 업데이트 되지 않아, 이미 조회했던 페이지를 영원히 조회하는 현상 발생 (무한 루프)
- 무한 루프를 도는 동안 커넥션을 계속 점유하기 때문에 최종적으로 커넥션 풀이 고갈됨

### to-be

```java
    private LocalDateTime updateLastFoundCreatedAt(Slice<Club> clubSlice, List<Club> result) {
        if (result.isEmpty()) {
            return clubSlice.getContent().get(clubSlice.getSize() - 1).getCreatedAt();
        }
        return result.get(result.size() - 1).getCreatedAt();
    }

    private Long updateLastFoundId(Slice<Club> clubSlice, List<Club> result) {
        if (result.isEmpty()) {
            return clubSlice.getContent().get(clubSlice.getSize() - 1).getId();
        }
        return result.get(result.size() - 1).getId();
    }
```
- 실제로 DB에서 마지막으로 읽은 데이터를 다음 조회 조건으로 설정하도록 변경
- 읽어온 페이지에 데이터가 없어도, 반드시 다음 페이지를 조회할 수 있게 됨
