### ISSUE TITLE
hibernate.dialect 속성 부재로 인한 배포 실패 현상 수정

### ISSUE THREAD

**Issue by J-I-H-O** [woowacourse-teams/2024-friendogly#758]
## 문제 사항
```
Caused by: org.hibernate.HibernateException: Unable to determine Dialect without JDBC metadata (please set 'jakarta.persistence.jdbc.url' for common cases or 'hibernate.dialect' when a custom Dialect implementation must be provided)
	at org.hibernate.engine.jdbc.dialect.internal.DialectFactoryImpl.determineDialect(DialectFactoryImpl.java:191)
	at org.hibernate.engine.jdbc.dialect.internal.DialectFactoryImpl.buildDialect(DialectFactoryImpl.java:87)
	at org.hibernate.engine.jdbc.env.internal.JdbcEnvironmentInitiator.getJdbcEnvironmentWithDefaults(JdbcEnvironmentInitiator.java:152)
	at org.hibernate.engine.jdbc.env.internal.JdbcEnvironmentInitiator.getJdbcEnvironmentUsingJdbcMetadata(JdbcEnvironmentInitiator.java:362)
	at org.hibernate.engine.jdbc.env.internal.JdbcEnvironmentInitiator.initiateService(JdbcEnvironmentInitiator.java:123)
	at org.hibernate.engine.jdbc.env.internal.JdbcEnvironmentInitiator.initiateService(JdbcEnvironmentInitiator.java:77)
	at org.hibernate.boot.registry.internal.StandardServiceRegistryImpl.initiateService(StandardServiceRegistryImpl.java:[130](https://github.com/woowacourse-teams/2024-friendogly/actions/runs/12198531844/job/34030645792#step:3:131))
	at org.hibernate.service.internal.AbstractServiceRegistryImpl.createService(AbstractServiceRegistryImpl.java:263)
```
- https://github.com/woowacourse-teams/2024-friendogly/actions/runs/12198531844/job/34030645792#logs
- hibernate.dialect 속성 추가

**Comment by J-I-H-O** [comment]
https://github.com/woowacourse-teams/2024-friendogly/pull/759#pullrequestreview-2484798046 코멘트 참고
